### ISSUE TITLE
is paged.js support vue.js3 ?

### ISSUE THREAD

**Issue by may820806** [pagedjs/pagedjs#117]
index.html
```html
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <link rel="icon" type="image/svg+xml" href="/vite.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title></title>
      </head>
      <body>
        <div id="app"></div>
        <script type="module" src="/src/main.ts"></script>
        <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
      </body>
    </html>
```

App.vue
```vue
<script setup lang="ts">
   import { Previewer } from 'pagedjs';
</script>
<template>
  <div class="pagedjs_pages">
     Lorem ipsum dolor, sit amet consec.......
     hellllloooooo!!!!!
  </div>
  <!-- hellllloooooo!!! disappeared  -->
```
css in App.vue
```css
@page {
  size: A4 landscape;
 // tried size: 297mm 210mm;
}
```

result:
what I expected is an A4 landscape page, but it seems like, the "page" is landscape, which is correct,  but the content is like vertical A4, and not showing my full content, cut the rest content at bottom, which part did I miss?
[![enter image description here][1]][1]
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/Id59q.jpg
  [2]: https://i.stack.imgur.com/1SuZh.png

**Comment by julientaq** [comment]
hi @may820806 welcome around.

i believe there is a wrong setup here.

the .pagedjs_pages element will be created by pagedjs. Same with the template. 

Here there seems to be a mix of different things.


If you want to use pagedjs on its own page, you use the polyfill, and it will do all the needed work.

if you want to use pagedjs in a dev env, then you need to use paged.js and run the script as you need  it. 

(an example from svelte here, but it’s the same setup imho. → https://github.com/pagedjs/pagedjs/issues/101)

that should help a bit to understand how it works. 

tell me how it goes, (i’m closing the issue as it’s asking for help more than a bug in paged.js which we’re happy to provide).

**Comment by may820806** [comment]
I found another[reference](https://github.com/rogerwang2014/vite-vue3-explore), for anyone who needs it.

```javascript
// App.vue

<script lang="ts">
  import { onMounted } from 'vue';
  
  onMounted(()=>{
    let paged = new Previewer();
  
    let flow = paged.preview().then((flow) => {
      console.log("Rendered", flow.total, "pages.");
    })
  });
</script>

<template ref="template">
  <div>hello</div>
</template>

<style lang="scss">
  @import 'pagedjs.scss';
</style>
```



```scss
// pagedjs.scss

@page {
  size: A4 landscape !important;

  @top-left {
    content: "should be shown on the top-left";
    font-size: 15px;
    color: #979797;
    text-align: left;
  }
}
// styling....

```
