### ISSUE TITLE
Pagedjs support for react js

### ISSUE THREAD

**Issue by sorin-sabo** [pagedjs/pagedjs#124]
Tried to use pagedjs together with react js:
- Installation works without any problem
Import however, it's simply not usable.
- In other examples I saw an import like: `import {} from 'pagedjs/dist/paged.polyfill';` - which of course generates an error
Is there a way to actually make it work with react js ?

**Comment by rohithmahesh3** [comment]
Hi, I don't know whether I'm the right person to answer this. But I did make it work for my project so just sharing my experience.

My html looks like this:

```html
<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
  <div id="preview_wrapper">
    <div id="preview"></div>
  </div>
</body>
```

Of course the root is used for rendering react app. In my case I didn't had to show the preview so in some way I had to hide it. So what I have come up with is to wrap the preview with another div with the following css. 

```css
#preview_wrapper {
  width: 0px;
  height: 0px;
  overflow: auto;
} 

@media print{
  #root{
    display: none;
  }
  #preview_wrapper{
    width: auto;
    height: auto;
    overflow: hidden;
  }
}
```

In react I created a `ref` and assigned it to the component that needs to be converted into pagedjs preview. 

```typescript
const ref = useRef<HTMLDivElement>(null)

useEffect(() => {
  previewer
    .preview(
      (ref.current?.innerHTML === null || ref.current!.innerHTML === '') ? '<div></div>' : ref.current!.innerHTML,
      [{
        _: `@page {
        size: A4;
        margin-top: 15mm;
        margin-bottom: 25mm;
        margin-left: 10mm;
        margin-right: 10mm;
    
        @top-right {
            content: counter(page)
        }
    
    }`}],
      document.querySelector("#preview")
    )
    .then((flow: any) => {
      console.log("preview rendered, total pages", flow.total, { flow });
    });
}, [ref, <other_dependencies>]);
```
```jsx
<div ref={<forwaredRefObj>}>
   {/* content */}
</div>
```

Hope this helps!
