### ISSUE TITLE
long image will be cut, how can i fix it

### ISSUE THREAD

**Issue by ChiaYuSu** [pagedjs/pagedjs#129]
html:
```html
<div class="section section-3 avoid-break force-break">
    <div class="row">
        <div>
            <img class="others-img" src="{{ url_for('static', filename='image/nccst.jpg') }}">
        </div>
        <div class="col">
            <h2>Test</h2>
            <p>
                Test 123
            </p>
            <p>
                Test 456
            </p>
        </div>
    </div>
    <div class="container-1">
        <img src="{{ url_for('static', filename='image/test.jpg') }}">
    </div>
</div>
```

css:
```css
.section {
    height: 982.672px !important;
    // overflow: hidden !important;
}

.container-1 {
    display: grid;
    justify-items: center;
    grid-gap: 10px;
    grid-template-columns: repeat(1, 1fr);
    margin: 0 auto;
}

.container-2 {
    display: grid;
    justify-items: center;
    align-items: center;
    grid-gap: 10px;
    grid-template-columns: repeat(2, 1fr);
    margin: 0 auto;
}

.section img {
    border-radius: 5px;
    object-fit: cover;
    width: 100%;
}
```

if i add `overflow: hidden !important;` in css file, will display
<img width="592" alt="image" src="https://user-images.githubusercontent.com/26423040/227605981-b1b2e7f5-6b8b-4f1f-99b7-07666ebf6d7a.png">
but the image is not fully presented

and if didn't add, will display
<img width="592" alt="image" src="https://user-images.githubusercontent.com/26423040/227605756-6875bac8-02df-4fa2-a324-318f3c4a4d2f.png">

the full image is as follows
![image](https://user-images.githubusercontent.com/26423040/227606385-5f12bf10-a210-4f4d-8bba-7d16cb8955b9.png)

-
I want to know how to
1. let the image complete display, and do not change the page
2. if the image is too long, it is automatically scaled to the height of the image

thank you, look forward to your reply
