### ISSUE TITLE
A method to avoid pagedjs_hyphen

### ISSUE THREAD

**Issue by jonculau** [pagedjs/pagedjs#168]
I need a solution to prevent hyphenation when using the pagedjs_hyphen class. Do you have any suggestions on how to achieve this?

**Comment by julientaq** [comment]
hey @jonculau what do you mean prevent hyphenation?

hyphenation is used when `hyphen: auto` rules show up in the css. 

you shouldn’t hav to worry about the `.pagedjs_hyphen` chlass 🤔 

would yu mind sharing the css of yours?

**Comment by jonculau** [comment]
Here's the relevant part of my css:
```css
*:not(code *) {
  font-family: Arial, Helvetica, sans-serif;
  color: #000000;
  hyphens: none;
}

td{
        word-wrap: break-word;
        word-break: none;
        break-inside: avoid !important;
        page-break-inside: avoid !important;
}

```

The hyphenization only appears with a page break, which also is not a desired behavior
![image](https://github.com/pagedjs/pagedjs/assets/58332309/0adf66af-53a9-4083-b3af-40e06e8581ae)
