### ISSUE TITLE
`counter(pages)` always returns `0`

### ISSUE THREAD

**Issue by hirasso** [pagedjs/pagedjs#173]
Hi there! Thank you for your work on this library!

I just started using it, maybe I'm missing something. I have the following CSS:

```css
@media print {
  @page {
    size: A4 portrait;
    margin: 7mm;
    // marks: crop cross;

    @bottom-center {
      content: "Page " counter(page) " of " counter(pages);
      font-size: 10pt;
    }
  }
}
```

It consistently prints the correct page number, but for `counter(pages)`, it's returning `0`:

![image](https://github.com/pagedjs/pagedjs/assets/869813/710e4cab-dcd5-42f3-bf96-049a7fd34765)

![image](https://github.com/pagedjs/pagedjs/assets/869813/8f85b70b-58fd-4c85-be49-5f72eed554bc)

[...]

![image](https://github.com/pagedjs/pagedjs/assets/869813/a0001dc8-bf2a-4874-af8f-3ed83dbcbe64)

and so on. 

I've tried using the custom css property `--pagedjs-page-count` instead, but that doesn't seem to work at all (and feels really hacky anyways 😅):

```css
.pagedjs_margin-bottom-center .pagedjs_margin-content::before {
  content: "Page " counter(page) " of " var(--pagedjs-page-count);
}
```

**Comment by hirasso** [comment]
This is very peculiar – the [example](https://gitlab.coko.foundation/pagedjs/refs-specifications/blob/master/counter-pages/counter-pages.html) is working just fine, but on my own site it's not working. Does anyone have an idea what could possibly interfere with the functionality?

**Comment by hirasso** [comment]
...found it! 🎉 I had this in one of my css files:

```css
my-custom-element {
  all: initial;
}
```

After removing this, `counter(pages)` now returns the correct number.

It would probably make sense to put a warning somewhere in the docs that `all: initial` will break the `pages` counter.
