### ISSUE TITLE
counters are stale on first page of a section.

### ISSUE THREAD

**Issue by RobMayer** [pagedjs/pagedjs#220]
I'm using the 0.5.0-beta.1

```css
@page main {
    @top-right-corner {
        content: counter(chapter-number, upper-roman);
    }
}

article {
    page: main;
}
h2 {
    page-break: before;
    counter-increment: chapter-number;
}
```

```html
<article>
    <h2>My Chapter Header</h2>
    <p>Some Content that will span more than one page</p>
</article>

```

the top right corner of the first page will have "0" for its content. All subsequent pages will have the correct "1".

it does not matter if I put the counter-increment on the h2 or the article.

it does not matter if the page-break goes on the article or on the h2

I tried using the example in the docs to work around this, but it seems that `content(before)` is not implemented (I question why that's in the docs if it's gone unimplemented for 6 years).

I also tried using a string-set using the counter directly.

```css
h2 {
    counter-increment: chapter-number;
    string-set: chapter-indicator counter(chapter-number, upper-roman);
}

@page main {
    @top-right-corner {
        content: string(chapter-indicator, first);
    }
}
```

but this rendered a literal "undefined"

What's the convention here?
