### ISSUE TITLE
cannot use multiple string() calls in a single content

### ISSUE THREAD

**Issue by RobMayer** [pagedjs/pagedjs#223]
currently using v0.5.0-beta.1 CLI

this works
```css
@page {
    @top-center {
        content: string(book-title);
    }
}
```

this also works
```css
@page {
    @top-center {
        content: string(book-version);
    }
}
```

this does not
```css
@page {
    @top-center {
        content: string(book-title) " - " string(book-version);
    }
}
```

and neither does this
```css
@page {
    @top-center {
        content: string(book-title) string(book-version);
    }
}
```

**Comment by RobMayer** [comment]
also, this works fine:

```css
@page {
    @bottom-left {
        content: counter(chapter-indicator, upper-roman) "." counter(section-indicator) " - " string(section-title, first);
    }
}
```

so I don't believe the issue is concatenation.
