### ISSUE TITLE
float: none on more specific selector doesn't prevent float: footnote from working

### ISSUE THREAD

**Issue by RobMayer** [pagedjs/pagedjs#224]
```css
cite {
    float: footnote;
}
figure cite {
    float: none;
}
```

`cite` elements outside of a Figure get moved to the footnotes area, as expected, but those within the figure element *also* get moved, even though float: none; is explicitly set.
