### ISSUE TITLE
direct descendent selector > breaks page declaration

### ISSUE THREAD

**Issue by RobMayer** [pagedjs/pagedjs#225]
```css
body > aside {
    page: interlude;
    break-before: page;
}
```

this will fall back to the generic page.
