### ISSUE TITLE
[Beta] Page 0 appearing in TOC

### ISSUE THREAD

**Issue by nbyloff** [pagedjs/pagedjs#240]
I am using the default TOC handler (shown below) with the latest pagedjs build. This does not happen in every PDF report I create, but noticed in longer reports the TOC will point to "page 0" for a couple sections in the middle of the report. What portion of the pagedjs library pulls the page # for a given HTML element? 

Also if i switch back to the latest non-beta release with the same report, the page #s are correct.

![Screenshot 2024-10-03 at 2 16 00 PM](https://github.com/user-attachments/assets/99928b7a-2c10-458c-aa42-b99afe01835d)

````
  window.createToc = function (config) {
    const content = config.content;
    const tocElement = config.tocElement;
    const titleElements = config.titleElements;

    let nqtls = {{ json_encode($failedNqtls ?? []) }};
    let tocElementDiv = content.querySelector(tocElement);
    let tocUl = document.createElement("ul");
    tocUl.id = "list-toc-generated";
    tocElementDiv.appendChild(tocUl);

    // add class to all title elements
    let tocElementNbr = 0;
    for (var i = 0; i < titleElements.length; i++) {

      let titleHierarchy = i + 1;
      let titleElement = content.querySelectorAll(titleElements[i]);


      titleElement.forEach(function (element) {

        // add classes to the element
        element.classList.add("title-element");
        element.setAttribute("data-title-level", titleHierarchy);

        // add id if doesn't exist
        tocElementNbr++;
        idElement = element.id;
        if (idElement == '') {
          element.id = 'title-element-' + tocElementNbr;
        }
        let newIdElement = element.id;

      });

    }

    // create toc list
    let tocElements = content.querySelectorAll(".title-element");

    for (var i = 0; i < tocElements.length; i++) {
      let tocElement = tocElements[i];
      console.log(tocElement); // nqtl 48 & 35 have page 0
      let tocNewLi = document.createElement("li");

      // Add class for the hierarcy of toc
      tocNewLi.classList.add("toc-element");
      tocNewLi.classList.add("toc-element-level-" + tocElement.dataset.titleLevel);

      // Keep class of title elements
      let classTocElement = tocElement.classList;
      for (var n = 0; n < classTocElement.length; n++) {
        if (classTocElement[n] != "title-element") {
          tocNewLi.classList.add(classTocElement[n]);
        }
      }

      // Create the element
      tocNewLi.innerHTML = '<a href="#' + tocElement.id + '">' + tocElement.innerHTML + '</a>';
      
      tocUl.appendChild(tocNewLi);
    }
  }

  class TOCHandler extends Paged.Handler {
    constructor(chunker, polisher, caller) {
      super(chunker, polisher, caller);
    }

    beforeParsed(content) {
      // generate TOC
      if (typeof window.parent.createToc === 'function') {
        window.parent.createToc({
          content: content,
          tocElement: '#my-toc-content',
          titleElements: ['h4.section-title', 'h5.section-title']
        });
      }
    }
  }
  Paged.registerHandlers(TOCHandler);
````

**Comment by nbyloff** [comment]
While debugging, I have fixed this issue by commenting out this line:

https://github.com/pagedjs/pagedjs/blob/main/src/utils/dom.js#L430 

````
if (result.hasAttribute("id")) {
    let dataID = result.getAttribute("id");
    result.setAttribute("data-id", dataID);
    //result.removeAttribute("id");
}
````

Commenting out removeAttribute fixes my TOC issue. Is this piece necessary for pagedjs? If the proper solution is to use `data-id` instead of `id`, I can make this change. However I am not sure why it only removes it for some chapters, and not all.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by nbyloff** [comment]
Switching from id to data-id did not solve my issue. for some reason, my TOC does page numbers for all pages but one specific line (5th element in TOC) gets a page #0. It places it's own "title-element-<number>" as the html id. And then runs the code snippet above. It only works if I keep the `result.removeAttribute("id")` commented out. 

I just don't know what that code is for and what it will impact doing so.

**Comment by julientaq** [comment]
hey @nbyloff you shouldn’t have to bother with data-id, as paged.js handles those.

can you put your html/css here?

**Comment by nbyloff** [comment]
Sure thing @julientaq thanks for looking. There's a ton of it since it produces a very large report, but I will start with the relevant code to pagedjs. 

The HTML below shows the second section in my report (h4) which produces like 15 sub-sections (h5). If there's something else specific you'd like to see let me know just trying to avoid posting everything. Most everything else else is report styling or unrelated to the TOC.

````html
<div class="page">
<div class="row mb-4">
  <div class="col-12">
    <h4 id="n_analysis" class="section-title">MY SECTION TITLE HERE</h4>
  </div>
</div>
  <h5 id="n_{{ UNIQUE SUB SECTION ID HERE }}" data-n-id="{{ SAME ID HERE I USE FOR SOMETHING ELSE }}" class="section-title">
    <u>{{ DYNAMIC SUB SECTION TITLE HERE }}</u></h5>
...
...
  </div>
</div>
````

````css
body {
  counter-reset: chapterNumber;
  font-family: 'Segoe UI', sans-serif;
}

h4.section-title {
  counter-increment: chapterNumber;
}

h4.section-title, h5.section-title {
    string-set: centerTitle content(text);
}

@media print {
      @page {
        size: letter landscape;
        @bottom-left {
          content: string(bizName);
          font-size: 8pt;
        }

        @bottom-center {
          content: string(centerTitle);
          font-size: 8pt;
        }
        @bottom-right-corner {
          content: "Page " counter(page) " of " counter(pages);
          font-size: 8pt;
        }
      }
    }
````


Side note, I changed the code to this to make it work for me:

````js
  if (result.hasAttribute("id")) {
      let dataID = result.getAttribute("id");
      result.setAttribute("data-id", dataID);
      result.removeAttribute("id");
      let found = document.querySelectorAll('[id=' + dataID + ']');
      if (found.length > 1) {
        result.removeAttribute("id");
      }
    }
````
