### ISSUE TITLE
Chromium 131 supports the CSS Paged Media Module Level 3 W3C specifications!

### ISSUE THREAD

**Issue by SuperPat45** [pagedjs/pagedjs#248]
I have just seen that the new version 131 of Chromium and its derivatives now support the W3C CSS Paged Media Module Level 3 specifications, on which paged.js is based:

https://developer.chrome.com/blog/print-margins

**Comment by scarlson1109** [comment]
### Code Changes (applied to `baseStyles` in paged.js)

Here's the minimal diff against v0.4.3. All changes are within the `baseStyles` template literal that `Polisher.insert()` injects as CSS.

**1. Ghost suppression — add to the existing `@media print` block (~line 27442):**

```css
@media print {
    /* ...existing Paged.js print rules... */

    /* NEW: Suppress Chrome 131+ native @page margin box rendering */
    @page {
        @top-left-corner { content: none !important; }
        @top-left { content: none !important; }
        @top-center { content: none !important; }
        @top-right { content: none !important; }
        @top-right-corner { content: none !important; }
        @bottom-left-corner { content: none !important; }
        @bottom-left { content: none !important; }
        @bottom-center { content: none !important; }
        @bottom-right { content: none !important; }
        @bottom-right-corner { content: none !important; }
        @left-top { content: none !important; }
        @left-middle { content: none !important; }
        @left-bottom { content: none !important; }
        @right-top { content: none !important; }
        @right-middle { content: none !important; }
        @right-bottom { content: none !important; }
    }
}
```

**2. Corner `::after` selector fix — extend the existing selector (~line 27324):**

```diff
 .pagedjs_pages .pagedjs_margin-left .pagedjs_margin-content::after,
 .pagedjs_pages .pagedjs_margin-top .pagedjs_margin-content::after,
 .pagedjs_pages .pagedjs_margin-right .pagedjs_margin-content::after,
-.pagedjs_pages .pagedjs_margin-bottom .pagedjs_margin-content::after {
+.pagedjs_pages .pagedjs_margin-bottom .pagedjs_margin-content::after,
+.pagedjs_pages .pagedjs_margin-top-left-corner .pagedjs_margin-content::after,
+.pagedjs_pages .pagedjs_margin-top-right-corner .pagedjs_margin-content::after,
+.pagedjs_pages .pagedjs_margin-bottom-left-corner .pagedjs_margin-content::after,
+.pagedjs_pages .pagedjs_margin-bottom-right-corner .pagedjs_margin-content::after {
     display: block;
 }
```

**3. Corner holder alignment — add `align-items: center` to the 4 existing corner holder rules (~lines 27026, 27034, 27071, 27079):**

```diff
 .pagedjs_margin-top-left-corner-holder {
     width: var(--pagedjs-margin-left);
     height: var(--pagedjs-margin-top);
     display: flex;
+    align-items: center;
     grid-column: left;
     grid-row: header;
 }
```

(Same change for `-top-right-corner-holder`, `-bottom-left-corner-holder`, `-bottom-right-corner-holder`.)

Fix 1 is the critical one — it resolves the ghost duplication. Fixes 2 and 3 address a pre-existing baseline alignment inconsistency between corner and non-corner margin boxes that became visible once the ghost was removed.
