### ISSUE TITLE
HTML with mixed orientations( potrait and landscape ) using pagedjs isn't working in browser's print window.

### ISSUE THREAD

**Issue by yogeshkashid2010** [pagedjs/pagedjs#281]
[paged-js-toc-example.txt](https://github.com/user-attachments/files/19499279/to-example.txt)

Please refer to the HTML example above with Paged.js and mixed orientation. When I try to print using window.print(), it generates the PDF in portrait mode only. I have attached a sample PDF here. Is there any configuration to respect each page's orientation in the Paged.js library?

[Complex Document with TOC (Offline).pdf](https://github.com/user-attachments/files/19499315/Complex.Document.with.TOC.Offline.pdf)

**Comment by zackpcodes** [comment]
This is kind of a hacky solution but i was able to resolve this by adding page at rules for named pages back to the css styles after pagedjs runs and making sure the landscape class is applied up the DOM tree

**Comment by yogeshkashid2010** [comment]
@zackpcodes: thank you for your reply!
Could you please share example or update my shared code and re-share it again here?

**Comment by julientaq** [comment]
right now we have a limitation with rotating pages, that comes from old chrome behavior (that wasn’t allowing rotating content)

i made a small script to add to pagedjs to handle that

you can use this css, after adding a class rotate to what needs to be rotated

```css

@page {
  size:  210mm 297mm;
}

/*for the ration*/
.rotate {
  page: rotate;
}

@page rotate {
  /*the size of the page has changed: width becomes height and height become width*/
  size: 297mm 210mm;
  margin: 20mm 30mm;

}

/*and for when paged.js is finished, we change the after rotation reading mode to be vertical-lr . and work our css to get back on track. `this is an example, you’ll have other css to fix imho*/

.afterRotated section {
  height: 100%;
  width: 100% !important;
  writing-mode: vertical-rl;
  transform: rotate(180deg);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: unset !important;

}



```

which will put the content on a named page `rotate`

then i use this hook to put everythng back in place when paged.js is finished (just add this js in a script tag after paged.js)

```js
class rotate extends Paged.Handler {
  constructor(chunker, polisher, caller) {
    super(chunker, polisher, caller);
  }
  afterRendered(pages) {
    for (const page of pages) {
      if (page.element.className.includes("rotate")) {
        console.log(page);
        // remove the rotate class
        page.element.classList.remove("pagedjs_rotate_page");
        page.element.classList.add("afterRotated");
      }
    }
  }
}
Paged.registerHandlers(rotate);
```

note that the page are rotated as chrome would do, but the content on it is rotated.

note also that it’s made with a class on the html, but we could define a css for that.


so it’s not a perfect fix, but a nice workaround untild paged.js evolve.
