### ISSUE TITLE
Improper footnote counter generated

### ISSUE THREAD

**Issue by zopyx** [pagedjs/pagedjs#59]
The footnotes have both the counter `2`

https://github.com/zopyx/print-css-rocks/tree/master/lessons/lesson-footnotes

<img width="536" alt="Bildschirmfoto 2022-03-01 um 19 01 24" src="https://user-images.githubusercontent.com/594239/156223555-9f22e3f2-2561-4198-bad6-e9c2d3da0557.png">

**Comment by julientaq** [comment]
Thanks for opening the issue!

**Comment by jcuenod** [comment]
I had the same issue. Removing this resolves it:

```css
::footnote-marker {
    content: counter(footnote, loweralpha) ". ";
}
```

But that is what is suggested in the release notes announcing footnote support
