### ISSUE TITLE
Superscript footnote markers

### ISSUE THREAD

**Issue by jcuenod** [pagedjs/pagedjs#66]
I need to make `::footnote-marker` superscript, but `::marker` only supports a limited set of CSS properties.

- I think I could use [`font-variant-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-position), but it doesn't seem to be supported by `paged.js`.
- I could use other `margin`/`vertical-alignment` tricks with `font-size`, but they don't work with `::marker`

Is there another way?

**Comment by julientaq** [comment]
Hi there

Paged.js support anything your browser supports. So if you dont have font variant position, it’s very likely that your font doesnt offer the feature. So change of font would be the simplest way to go.

But it’s far from ideal. 

The `::footnote-marker` we’re polyfilling shouldn’t be a marker because of those limitation, you’re right. 

Until we get to change that, i think you could try the following:

```css

/* hide the marker as you prefer (the display non doesnt seem to work though) */
[data-footnote-marker]::marker {
  display: none; 
  color: transparent;
}

/* Make the footnote relative to move the future footnote call */
[data-footnote-marker] {
  position: relative;
}


/* do your style changes*/
[data-footnote-marker]::before {
  content: counter(footnote,loweralpha) ". ";
  color: purple;
  font-weight: 700;
  position: absolute;
  font-size: .6em;
  display: block;
  top: 0;
}
```

<img width="842" alt="image" src="https://user-images.githubusercontent.com/2174473/162398981-88157a9e-09c4-4994-a513-d19fccbd5772.png">

I mark this as a question.

**Comment by jcuenod** [comment]
Using the `::before` pseudo-element is a good idea, but it produces #59.

**Comment by julientaq** [comment]
Right.

I looked at the code, try using `footnote-marker` instead of `marker`, it seems to work.
I’ll see to update our code as it would explaine why thngs get wrong.

```
.footnote::footnote-marker {
    content: counter(footnote-marker, lower-roman);
    font-size: 14pt;
    color: blue;
}
```

**Comment by jcuenod** [comment]
Using `counter(footnote-marker, lower-roman)` instead of `counter(footnote, lower-roman)` fixes the numbering, thanks! I'm guessing that this introduces a risk of losing sync between `footnote-call` and `footnote-marker`, though.

**Comment by julientaq** [comment]
i’m not so sure, but it’s indeed something to have a look at. 

Anyway, we’ll fix the `footnote` keyword as it’s what the w3c is asking for

**Comment by jcuenod** [comment]
Using the `::fotnote-marker` pseudo-element doesn't seem to be helping with positioning the number.

**Comment by julientaq** [comment]
Ah shoot sorry, i havent been clear  (that’s the issue when mixing issues :D)

try this:

```css

  .footnote::footnote-marker {
        content: counter(footnote, lower-roman);
        font-size: 14pt;
        color: blue;
        display: none;
        color: transparent;
        visibility: invisible;
      }
      
```

and tell me how it goes
