### ISSUE TITLE
Multi-Paragraph Footnotes

### ISSUE THREAD

**Issue by jcuenod** [pagedjs/pagedjs#68]
I have a number of footnotes that have more than one paragraph. It seems that the design for `pagedjs` is to support the content of the footnote in a `<span>` and that `<p>` elements belong in the main body.

Am I understanding correctly? If so would you recommend use `<br />`? I need paragraphing because I need `text-indent` so `<br />` might not solve my problem.

**Comment by julientaq** [comment]
hi there.

So yeah, <br/> is not the right path.

But you can’t have a `<div>`  inside a paragraph in terms of validation (that’s why we belive we should have a `<note>` element in the HTML that would be available everywhere).

The way footnotes are implemented, you can’t have `<div>`. You could have `<span>` into `<span>` though but you can’t really have them display as blocks either. 

This is a simple example of how to make it work today, and marking the issue as a discussion too.

```css
[data-footnote-marker]::marker {
 display: none; 
  color: transparent;
}

[data-footnote-marker] {
  position: relative;
}

[data-footnote-marker]::before {
  content: counter(footnote,loweralpha) ". ";
  color: purple;
  font-weight: 700;
  position: absolute;
  font-size: .6em;
  display: block;
  top: 0;
}

.pagedjs_footnote_inner_content >.footnote > span {
 display: block; 
  margin-left: 2ch;
}
.pagedjs_footnote_inner_content >.footnote > span:first-of-type {
  display: inline; 
  margin-left: 0ch;
}
```

<img width="842" alt="image" src="https://user-images.githubusercontent.com/2174473/162402426-9986ec6c-b427-4f41-a359-b0833c4b48be.png">
