### ISSUE TITLE
resetting footnote counter resets each table of content chapter page number

### ISSUE THREAD

**Issue by Wisplike** [pagedjs/pagedjs#91]
I have a document with footnotes and a table of content with auto generated page numbers.
```css
@page {
  counter-reset: footnote 0;
}

.toc-chapter::after {
  content: target-counter(attr(href url), page);
}
```
Adding the `counter-reset: footnote 0;` makes the generated content value 0 in all of the table of contents.
